### PR TITLE
Fix faucet's alert width

### PR DESCRIPTION
**Pull request by samuel-uniris**
# Description

After the implementation of the faucet's limiter, the text of the alert in case of error flow outside the banner, because
the alert size have been hard-coded.

This is a simple fix, to put the size of the faucet's  alert to 100%

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

Go the faucet, emit more than 3 transactions and you should see the alert taking the entire screen

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by blackode — APPROVED** [review]
Yes, Width is now 100 %
image

**Comment by blackode** [comment]
I also see there are good notification sections in **Bulma**.

**Comment by blackode** [comment]
## Info Notification
After submitting the transaction notification
The `X` at the corner is used to close the notification.

image

## Error Notification
image

**Review by prix-uniris — APPROVED** [review]
looks good to me

**Pull request merged**
