### PR TITLE
Changed host ip to 0.0.0.0 for dev environment

### PR DESCRIPTION
**Pull request by roychowdhuryrohit-dev**

### CODE REVIEW

**Comment by samuel-uniris** [comment]
I think just updating the env var should be sufficient. As it may be specific.

**Comment by roychowdhuryrohit-dev** [comment]
Okay thanks. Actually the default behaviour in popular http servers is to host at the 0.0.0.0 undefined address so that it’s accessible from all interfaces.

**Comment by samuel-uniris** [comment]
Yes I know just this static IP is used for the p2p discovery inside node transaction.
For accepting incoming request on the web part , maybe see the Phoenix.Endpoint configuration. https://hexdocs.pm/phoenix/Phoenix.Endpoint.html

**Comment by roychowdhuryrohit-dev** [comment]
Okay I create a new PR with phoenix config.

**Pull request closed without merging**
