### PR TITLE
Poll metrics Bug. Resolves #370.

### LINKED ISSUE #370: Poll metrics Error in metrics dashboard during node start
### What happened?

Screenshot 2022-06-09 125910

Maybe the metrics polling process started before the transaction_validation and it got empty so, it is unable to poll metrics

### What is expected ?

It expected to start normally and give the `archethic_mining_full_transaction_validation_duration => val `, similarly others metrics etc

### PR DESCRIPTION
**Pull request by apoorv-2204**
# Description

Includes acc in Enum.reduce
Fixes # (#370)

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

- [x] No error reported during /metrics/dashboard

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by samuel-uniris — COMMENTED** [review]
I think you can simplify to avoid creation of a module for a single function, and just create a function in `utils` to be something like: `merge_list_of_maps/1`, where you could apply doc tests as it's public function. So this could be used by other components

**Comment by samuel-uniris** [comment]
> > I think you can simplify to avoid creation of a module for a single function, and just create a function in `utils` to be something like: `merge_list_of_maps/1`, where you could apply doc tests as it's public function. So this could be used by other components
> 
> I created this module , in future prospect for data mutation and to resolve to_map and from_map.

Do not overengineer and foresee too much, we might not even remember it, so you can either use private fn or use already existing module like utils. So it's simple to manage.

**Comment by apoorv-2204** [comment]
> > > I think you can simplify to avoid creation of a module for a single function, and just create a function in `utils` to be something like: `merge_list_of_maps/1`, where you could apply doc tests as it's public function. So this could be used by other components
> > 
> > 
> > I created this module , in future prospect for data mutation and to resolve to_map and from_map.
> 
> Do not overengineer and foresee too much, we might not even remember it, so you can either use private fn or use already existing module like utils. So it's simple to manage.
> 
> We could refactor later in any case

Agreed Noted,
But actually, I saw we had too many methods for data mutation spread over different modules.

**Comment by samuel-uniris** [comment]
> > > > I think you can simplify to avoid creation of a module for a single function, and just create a function in `utils` to be something like: `merge_list_of_maps/1`, where you could apply doc tests as it's public function. So this could be used by other components
> > > 
> > > 
> > > I created this module , in future prospect for data mutation and to resolve to_map and from_map.
> > 
> > 
> > Do not overengineer and foresee too much, we might not even remember it, so you can either use private fn or use already existing module like utils. So it's simple to manage.
> > We could refactor later in any case
> 
> Agreed Noted, But actually, I saw we had too many methods for data mutation spread over different modules.

Data mutation/transformation is the core of functional programming, so it's kind of obvious to use them in different places. The issue of many places, it's when something is really recurrent and with the same behavior. But for data transformation, often, need to be adapted for a given context, it might the interpretation or the expected result

**Comment by apoorv-2204** [comment]
> > > > > I think you can simplify to avoid creation of a module for a single function, and just create a function in `utils` to be something like: `merge_list_of_maps/1`, where you could apply doc tests as it's public function. So this could be used by other components
> > > > 
> > > > 
> > > > I created this module , in future prospect for data mutation and to resolve to_map and from_map.
> > > 
> > > 
> > > Do not overengineer and foresee too much, we might not even remember it, so you can either use private fn or use already existing module like utils. So it's simple to manage.
> > > We could refactor later in any case
> > 
> > 
> > Agreed Noted, But actually, I saw we had too many methods for data mutation spread over different modules.
> 
> Data mutation/transformation is the core of functional programming, so it's kind of obvious to use them in different places. The issue of many places, it's when something is really recurrent and with the same behavior. But for data transformation, often, we need to adapt it for a given context, it might change the interpretation or the expected result

Is it a good idea to generalize from_map and to_map for structs?

**Pull request merged**
