### PR TITLE
use PlugCrypto binary to term in bootstrap.info

### PR DESCRIPTION
**Pull request by apoorv-2204**
though its not user-data , but still.

### CODE REVIEW

**Review by bchamagne — APPROVED** [review]
I am fine with this, maybe we can add a Credo rules to forbid the usage of `binary_to_term` alltogether.

**Comment by apoorv-2204** [comment]
> maybe we can add a Credo rules to forbid

Credo do has high priority warning, but as of now we are just ignoring it.

**Comment by Neylix** [comment]
If there is configuration that ignore this check, we should not ignore it. Could you update the conf to ensure credo raise a warning if there is a binary to term used ?

**Comment by apoorv-2204** [comment]
> If there is configuration that ignore this check, we should not ignore it. Could you update the conf to ensure credo raise a warning if there is a binary to term used ?

There are also other critical issues reported by credo,  aka priority high . Exiting the credo at priority high will eventually crash as they are not fixed yet

**Comment by Neylix** [comment]
> > If there is configuration that ignore this check, we should not ignore it. Could you update the conf to ensure credo raise a warning if there is a binary to term used ?
> 
> There are also other critical issues reported by credo, aka priority high . Exiting the credo at priority high will eventually crash as they are not fixed yet

Do you mean Credo or Sobelow ?

**Comment by apoorv-2204** [comment]
> > > If there is configuration that ignore this check, we should not ignore it. Could you update the conf to ensure credo raise a warning if there is a binary to term used ?
> > 
> > 
> > There are also other critical issues reported by credo, aka priority high . Exiting the credo at priority high will eventually crash as they are not fixed yet
> 
> Do you mean Credo or Sobelow ?

credo

**Pull request merged**
