### PR TITLE
Add transaction's content verification

### LINKED ISSUE #409: Provide a better validation for typed transaction
### Is your feature request related to a problem?

Today we have several types of transactions for user:
- `transfer` 
- `hosting`
- `token`
- ...

Even if the types are just a functional meaning and have some relation to the replication scheme and validation context, we should enforce some transaction data structure requirements.

### Describe the solution you'd like

So you can add some minimal criteria for a given type to be respected.
For instance:
- transfer's transaction should contain at least one UCO or Token transfer
- hosting should match the Archethic web deployment format.

But we should probably define another type of transaction for user, when someone doesn't know in which predefined type the transaction should belong for example: smart contract, authorization and encrypted data, etc…

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by samuelmanzanera**
# Description

This PR improves data validation for transfer & hosting tx
For the hosting, this is based on the changes from https://github.com/archethic-foundation/aeweb-cli/pull/87

Fixes #409 

## Type of change

- New feature (non-breaking change which adds functionality)

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by bchamagne — CHANGES_REQUESTED** [review]
It does not work because it tries to validate the data transaction with the same schema. 
AEWebCLI's data transaction format did not change and looks like this:

```
%{
  "dir1" => %{
    "file10.txt" => "H4sIAAAAAAAAA0vLzElVMDTgAgALt2T5CAAAAA",
    "file11.txt" => "H4sIAAAAAAAAA0vLzElVMDTkAgBKhn_gCAAAAA"
  },
  "dir2" => %{
    "hello.txt" => "H4sIAAAAAAAAA_NIzcnJ1yupKFHQyM_LqVRIy8xJVcjMU0jJLDLS5AIAt5R0vB4AAAA"
  },
  "dir3" => %{
    "index.html" => "H4sIAAAAAAAAA7PJMLRz8QwyVsjMS0mt0Msoyc2x0QeKcQEAL-DoARkAAAA"
  },
  "file1.txt" => "H4sIAAAAAAAAA0vLzElVMFTgAgBapaazCAAAAA",
  "file2.txt" => "H4sIAAAAAAAAA0vLzElVMOICAMGeIz8HAAAA",
  "file3.txt" => "H4sIAAAAAAAAA0vLzElVMOYCAICvOCYHAAAA"
}
```

2022-12-06 14:07:05.340 [debug] Invalid AEWeb format [{"Required properties aewebVersion, metaData were not present.", "#"}]

@samuelmanzanera , I'll deal with this

**Comment by bchamagne** [comment]
The issue was because the json schema was created for this data transaction format:

```
%{
  "dir1/file10.txt" => "H4sIAAAAAAAAA0vLzElVMDTgAgALt2T5CAAAAA",
  "dir1/file11.txt" => "H4sIAAAAAAAAA0vLzElVMDTkAgBKhn_gCAAAAA",
  "dir2/hello.txt" => "H4sIAAAAAAAAA_NIzcnJ1yupKFHQyM_LqVRIy8xJVcjMU0jJLDLS5AIAt5R0vB4AAAA",
  "dir3/index.html" => "H4sIAAAAAAAAA7PJMLRz8QwyVsjMS0mt0Msoyc2x0QeKcQEAL-DoARkAAAA",
  "file1.txt" => "H4sIAAAAAAAAA0vLzElVMFTgAgBapaazCAAAAA",
  "file2.txt" => "H4sIAAAAAAAAA0vLzElVMOICAMGeIz8HAAAA",
  "file3.txt" => "H4sIAAAAAAAAA0vLzElVMOYCAICvOCYHAAAA"
}
```

This format has been discussed but it is not implemented like this yet. Current format is: 
```
%{
  "dir1" => %{
    "file10.txt" => "H4sIAAAAAAAAA0vLzElVMDTgAgALt2T5CAAAAA",
    "file11.txt" => "H4sIAAAAAAAAA0vLzElVMDTkAgBKhn_gCAAAAA"
  },
  "dir2" => %{
    "hello.txt" => "H4sIAAAAAAAAA_NIzcnJ1yupKFHQyM_LqVRIy8xJVcjMU0jJLDLS5AIAt5R0vB4AAAA"
  },
  "dir3" => %{
    "index.html" => "H4sIAAAAAAAAA7PJMLRz8QwyVsjMS0mt0Msoyc2x0QeKcQEAL-DoARkAAAA"
  },
  "file1.txt" => "H4sIAAAAAAAAA0vLzElVMFTgAgBapaazCAAAAA",
  "file2.txt" => "H4sIAAAAAAAAA0vLzElVMOICAMGeIz8HAAAA",
  "file3.txt" => "H4sIAAAAAAAAA0vLzElVMOYCAICvOCYHAAAA"
}
```

Here's my suggestion to fix with current data transaction format: [jsonschema.patch.tar.gz](https://github.com/archethic-foundation/archethic-node/files/10167756/jsonschema.patch.tar.gz)

**Comment by apoorv-2204** [comment]
> # Description
> This PR improves data validation for transfer & hosting tx For the hosting, this is based on the changes from [archethic-foundation/aeweb-cli#87](https://github.com/archethic-foundation/aeweb-cli/pull/87)
> 
> Fixes #409
> 
> ## Type of change
> * New feature (non-breaking change which adds functionality)
> 
> # Checklist:
> * My code follows the style guidelines of this project
> * I have performed a self-review of my own code
> * I have commented my code, particularly in hard-to-understand areas
> * I have made corresponding changes to the documentation
> * My changes generate no new warnings
> * I have added tests that prove my fix is effective or that my feature works
> * New and existing unit tests pass locally with my changes
> * Any dependent changes have been merged and published in downstream modules

https://github.com/archethic-foundation/aeweb-cli/pull/87
This pr doesnt impl key value pair.It uses nested json struct with metaData props

**Review by bchamagne — APPROVED** [review]
Hello, I did the quick fix after the big merge of all AEWeb PRs. 
This is ready to merge !

Tested with AEWEB CLI

**Comment by samuelmanzanera** [comment]
> Hello, I did the quick fix after the big merge of all AEWeb PRs. This is ready to merge !
> 
> Tested with AEWEB CLI

Thanks :+1:

**Review by Neylix — APPROVED** [review]

**Pull request merged**
