### PR TITLE
Add default `code_change/4` in GenStateMachine

### PR DESCRIPTION
**Pull request by samuelmanzanera**
# Description

During hot upgrades, GenServer handle default code_change,
however, GenStateMachine does not.

Hence, we have to add a default one to make the upgrade successful

## Type of change

Please delete options that are not relevant.

- Enhancement

# How Has This Been Tested?

Using this script: `local_release.sh`

```sh
#!/bin/bash

UPGRADE=0
usage() {
  echo "Usage:"
  echo ""
  echo " Release Archethic node binary"
  echo ""
  echo "  " local_release.sh" Install the release"
  echo "  " local_release.sh -u "       Upgrade the release"
  echo ""
}

while getopts :suhd: option
do
    case "${option}"
    in
        u) UPGRADE=1;;
        h)
          usage
          exit 0
          ;;
        *)
          usage
          exit 1
          ;;
    esac
done
shift $((OPTIND -1))

VERSION=$(grep 'version:' mix.exs | cut -d '"' -f2)

if [ $UPGRADE == 1 ]
then
    mix distillery.release --upgrade
    echo "Copy upgraded release into ../archethic-release/releases/${VERSION}"
    mkdir -p ../archethic-release/releases/$VERSION
    cp _build/dev/rel/archethic_node/releases/$VERSION/archethic_node.tar.gz ../archethic-release/releases/$VERSION/archethic_node.tar.gz

    echo "Run the upgrade"
    ../archethic-release/bin/archethic_node upgrade $VERSION
else
    mix distillery.release
    mkdir -p ../archethic-release
    tar zxvf _build/dev/rel/archethic_node/releases/$VERSION/archethic_node.tar.gz -C ../archethic-release
    echo "Release has been installed on ../archethic-release"
fi
```

Then create the first release: 
```bash
./local_release.sh
```

Then start the node
```bash
../archethic-release/bin/archethic-node console
```

Change the mix version
And run the upgrade
```bash
./local_release.sh -u
```

It should have error about the release handler

Without this fix, you will end up with some error like: `{:code_change_failed, _module, _, :undefined}`

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by bchamagne** [comment]
Script is not creating the ../archethic-release folder on the first run (./local_release.sh)
Add `mkdir -p ../archethic-release` line 44 of the script (before the `tar`)

**Comment by bchamagne** [comment]
Didn't you missed `Archethic.Mining.DistributedWorkflow` state machine?

**Comment by samuelmanzanera** [comment]
> I did not encounter any `{:code_change_failed, _module, _, :undefined}` but I have the following recurring error:
> 
> ```
> 2022-11-17 08:24:00.323 [error] GenServer {Archethic.BeaconChain.SubsetRegistry, <<29>>} terminating
> ** (File.Error) could not write to file "/home/bastien/Chamagne/archethic/archethic-release/lib/archethic-10.26.0/data_node1/slot_backup": no such file or directory
>     (elixir 1.14.1) lib/file.ex:1104: File.write!/3
>     (archethic 10.26.0) lib/archethic/beacon_chain/subset.ex:159: Archethic.BeaconChain.Subset.handle_info/2
>     (stdlib 4.1.1) gen_server.erl:1123: :gen_server.try_dispatch/4
>     (stdlib 4.1.1) gen_server.erl:1200: :gen_server.handle_msg/6
>     (stdlib 4.1.1) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
> Last message: {:create_slot, ~U[2022-11-17 08:24:00Z]}
> ```
> 
> This happens because the `data_node1/` directory does not exist in the new application path.

Yes this is a problem with dev env, as the data directory is on the release folder itself but on externalize. 
On prod environment this is fixed.

**Comment by samuelmanzanera** [comment]
> Didn't you missed `Archethic.Mining.DistributedWorkflow` state machine?

Yes I can add it, evenif the state of this process is short term

**Review by bchamagne — APPROVED** [review]

**Pull request merged**
