### PR TITLE
Update opt25 fork distillery

### PR DESCRIPTION
**Pull request by cluster**
# Description

The goal of this PR is to update OTP to version 25.
Since distillery isn't compatible with OTP25 (and is no longer active), a [fork](https://github.com/archethic-foundation/distillery) has been made to fix the issue.

We could also remove distillery from the project, but because hot code upgrade is necessary (and distillery has so much tools for it), we had to keep it.

⚠️ [The distillery PR](https://github.com/archethic-foundation/distillery/pull/1) needs to be merged and `mix deps.update distillery` needs to be run (and the new mix.lock needs to be commited) before merging this PR.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- New feature (non-breaking change which adds functionality)

# How Has This Been Tested?

Tested locally and with the docker image. Doing transactions...

# Checklist:

- My code follows the style guidelines of this project
- I have performed a self-review of my own code
- I have commented my code, particularly in hard-to-understand areas
- I have made corresponding changes to the documentation
- My changes generate no new warnings
- I have added tests that prove my fix is effective or that my feature works
- New and existing unit tests pass locally with my changes
- Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Review by samuelmanzanera — APPROVED** [review]

**Comment by apoorv-2204** [comment]
OTP 25 :+1:

**Comment by samuelmanzanera** [comment]
Test with `mix distillery.release` => 👍

**Comment by cluster** [comment]
> We just got the error on the test to resolve.

I was hopping it was due to a problem on my local environment 😅
It's so strange because when I add
```
{a, _} = :erlang.process_info(self(), :message_queue_data)
IO.puts(a)
```
to the test, it just works... 🤷‍♂️

I'm going to investigate to find out the source of this issue 🤔

**Comment by samuelmanzanera** [comment]
Tests passed now

**Comment by samuelmanzanera** [comment]
Tested with hot reload (distillery upgrades)

**Pull request merged**
